// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOT_2fdpWOqAF5NNH-pUSnD6P0_25s_C0',
    appId: '1:615004966903:web:8b75ff560e25a840f028f2',
    messagingSenderId: '615004966903',
    projectId: 'sparky-scouts',
    authDomain: 'sparky-scouts.firebaseapp.com',
    storageBucket: 'sparky-scouts.appspot.com',
    measurementId: 'G-726ZYV6BHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Rsl6mUhwhGeAt3YDiKpQ7H2EvDP7rgg',
    appId: '1:615004966903:android:4c7860ff33577e9bf028f2',
    messagingSenderId: '615004966903',
    projectId: 'sparky-scouts',
    storageBucket: 'sparky-scouts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkng3ZoR3lobQrQf1lw6x7h09-3n6tgvY',
    appId: '1:615004966903:ios:7e77be0c5bfc553cf028f2',
    messagingSenderId: '615004966903',
    projectId: 'sparky-scouts',
    storageBucket: 'sparky-scouts.appspot.com',
    iosClientId:
        '615004966903-99oo52u17lpfjd95uep83pip1i2hk4ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkyScouts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkng3ZoR3lobQrQf1lw6x7h09-3n6tgvY',
    appId: '1:615004966903:ios:7e77be0c5bfc553cf028f2',
    messagingSenderId: '615004966903',
    projectId: 'sparky-scouts',
    storageBucket: 'sparky-scouts.appspot.com',
    iosClientId:
        '615004966903-99oo52u17lpfjd95uep83pip1i2hk4ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkyScouts',
  );
}
